dist: trusty
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libgtest-dev
script: export CC=gcc-5 CXX=g++-5; make && make -C tests && cd tests && ./test-all
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: pCMGXBhP6St/UlKA6LyuNAoPy7Hs4zSQLH16zI5wmiMAqBowCtoEnWcd1Rt3+ya3T9zy8DtD6rNIsAkH18tQQK1lGahIvwiicGMUFNLPROdaTbczekBU/qI7xccorqGVGRaM1sfJCb5M7tkb4MuTx+p7gCwd29/9b9yXICNIHIuyyD7BP4kr+JfBLXLEt70P7qWV0xEzGwlEL3jmFLodWWIMR1z+YYu5cjIqY5NUuT3w4WdLwMgySlbQ1pizNHPlauhJfh0XOAReZvpF2QQrQXfrOr4TNNMEC6cYJKYqtBZD4ZSGYqK343uHm/6jKfRfpKgXHGHy2gT9I2WsYkmRDXGPcvab4Mhfbj8+KaRZuJbidhqkks3L6QrDYodojHjFLnSQH2ttAESFi0ZZMi+pzutBAXv0UkFv8dnDpAABEztOb1V0EuRuXvM+ZhJDKq3JgRQco6P+plK9IcFeWxK8pHiVtWlJBWgVSw2V9+x8VzfNVdXNMWGvRBtdpPyOjpPUi/NxBaZLcNQIRHPZIehp6cqUJGXno3gVNjj8MVZpNu1Ogvgzs4M0NDOLZFyDjPUhlT5lphYUoPnlITbSQzke34GjWm3HrcY2zPkaXEodYkkep1PShJon6HayFZUdRd4+LZhqyAaWN2AEhXcKv1BNpQ1iNFO6/d5fkfmDFj8QkuU=
  file: peercast-yt-linux-x86_64.tar.gz
  skip_cleanup: true
  all_branches: true
  on:
    repo: plonk/peercast-yt
    tags: true
